### ISSUE TITLE
Future

### ISSUE THREAD

**Issue by Hoverbear** [Hoverbear/raft#13]
CC @danburkert How does this look for a plan for the next week or so?

0. [x] Get `master` working.
1. [x] Cherry-pick state machine changes from https://github.com/danburkert/raft/tree/state-machine into Master.
2. [ ] Code review and clarification. Keeping true to the Raft paper wherever possible
  - I noticed, for example, [this](https://github.com/danburkert/raft/blob/8ab2eb087edcd1c30c26e659a0b6c3c345c6c408/src/messenger.rs#L5) is perhaps incorrect.
3. [ ] ~~Use Cap'n Proto RPCs instead of structs. (@hoverbear volunteers)~~
4. [ ] Firm up interfaces and build tests/examples.

**Comment by danburkert** [comment]
Looks good to me.  Merging my state-machine branch is going to be tough, since the code is pretty much a rewrite, but it doesn't implement most of the Raft functionality (way less than the existing master).  Perhaps it would be easier/cleaner to just cherry pick out the good ideas from that branch and merge them over manually.

**Comment by danburkert** [comment]
Also,  `messenger.rs` is not used, that was leftover from an earlier iteration.  The real implementation of that is [here](https://github.com/danburkert/raft/blob/state-machine/src/transport.rs), and is essentially a hand rolled RPC system.  I think it is correct to retry failed RPCs indefinitely, I remember the paper saying that but I need to go back and look.

**Comment by Hoverbear** [comment]
Okay lets cherry pick then. I will work on RPC this week. Would you be willing to work on the state-machine things since I'm not totally familiar with what's ready?

**Comment by Hoverbear** [comment]
@danburkert Do you think we should merge the MIO repo? I got it building tonight. It is `old_io` free and is probably much farther along than `master` even though it's not fully implemented.

**Comment by Hoverbear** [comment]
@danburkert Do you think the client interface we discussed would be between non-participants in Raft and Raft Nodes, or just between Raft nodes?

**Comment by Hoverbear** [comment]
@danburkert Please make sure to mark incomplete functions with `unimplemented!()`, thanks!

**Comment by Hoverbear** [comment]
@danburkert I did some integration tonight. Most of `RaftNode` has been stripped down to just network related functionality. I've also added some primitive TCP handling, I suspect once things start working we can move to persisted streams.
