### ISSUE TITLE
Create `RaftError`

### ISSUE THREAD

**Issue by Hoverbear** [Hoverbear/raft#21]
You can only return one type of error, however Raft frequently deals with `io::Result` and `capnp::Result`, as well as having some of it's own error states not related. In order to effectively pass up errors, we need to have our own error type.

This will require building some error infrastructure. Probably implementing [`FromError`](https://doc.rust-lang.org/std/error/#the-fromerror-trait) for the created enum.

**Comment by Hoverbear** [comment]
I implemented this in `Raft` however it could probably be extended and used in `RaftNode` and others.

**Comment by danburkert** [comment]
This is pretty much compete.
