### ISSUE TITLE
Design Notes

### ISSUE THREAD

**Issue by danburkert** [Hoverbear/raft#24]
This is an overview of the architecture of the `raft` library. Familiarity with the [Raft Consensus Algorithm](https://raftconsensus.github.io/) is assumed.

From a user perspective, there are three fundamental components of the `raft` library: the `StateMachine`, the `Server`, and the `Client`. Subsequent sections will detail these components individually, and their interactions.

## StateMachine

[`StateMachine`](https://hoverbear.github.io/raft/raft/state_machine/trait.StateMachine.html) is a Rust trait, which users of the `raft` library must provide. A `StateMachine` is a single instance of a distributed application. It is the `raft` libraries responsibility to take commands from the `Client` and apply them to each `StateMachine` instance in a globally consistent order.

The `StateMachine` is interface is intentionally generic so that any distributed application needing consistent state can be built on it.  For instance, a distributed hash table application could implement `StateMachine`, with commands corresponding to `insert`, and `remove`. The `raft` library would guarantee that the same order of `insert` and `remove` commands would be seen by all replicas.

## Server

`Server` is a Rust type which is responsible for coordinating with other remote `Server` instances, responding to commands from the `Client`, and applying commands to a local `StateMachine` replica. A `Server` may be a `Leader`, `Follower`, or `Candidate` at any given time as described by the Raft Consensus Algorithm.

### Internals

In order to implement the Raft Protocol, the `Server` must respond to events (messages from other `Server` or `Client` instances, as well as timeouts) in highly context-dependent ways. We found while trying to implement the `Server` that mixing Raft Protocol logic with network logic led to incomprehensible and unmaintainable code. Accordingly, we decomposed the problem into an inner [`Replica`](https://github.com/Hoverbear/raft/blob/master/src/replica.rs) type which is responsible for the Raft Protocol logic, which left the `Server` only responsible for receiving and dispatching events.

#### `Replica` Implementation

The `Replica` is a state-machine (not to be confused with the `StateMachine` trait) which implements the logic of the Raft Protocol. A `Replica` receives events from the local `Server`.  The set of possible events is specified by the Raft Protocol:

````
Event = AppendEntriesRequest | AppendEntriesResponse
      | RequestVoteRequest | RequestVoteResponse
      | ElectionTimeout | HeartbeatTimeout
      | ClientCommand
````
In response to receiving an event, the `Replica` may mutate its own state, apply a command to the local `StateMachine`, or return an event to be sent to one or more remote `Server` or `Client` instances.

#### `Server` Implementation

The `Server` is responsible for receiving events from remote `Server` or `Client` instances, as well as setting election and heartbeat timeouts.  When an event is received, it is applied to the local `Replica`. The `Replica` may optionally return a new event which must be dispatched to either the `Server` or `Client` which sent the original event, or to all `Server` instances.

Because messages are passed asyncronously between `Server` instances, a `Server` could get into a situation where multiple events are ready to be dispatched to a single remote `Server`. In this situation, the `Server` will replace the existing event with the new event, except in one special circumstance: if the new and existing messages are both `AppendEntryRequest`s with the same `term`, then the new message will be dropped.

## Client

The `Client` allows users of the `raft` library to connect to remote `Server` instances and issue commands to be applied to the `StateMachine`.

**Comment by danburkert** [comment]
|existing event type|new event type|action|
|---|---|---|
|`AppendEntriesRequest`|`AppendEntriesRequest`|drop the new event|
|`AppendEntriesRequest`|`AppendEntriesResponse`|drop the existing event|
|`AppendEntriesRequest`|`RequestVoteRequest`|drop the existing event|
|`AppendEntriesRequest`|`RequestVoteResponse`|drop the existing event*|
|`AppendEntriesResponse`|`AppendEntriesRequest`|drop the existing event|
|`AppendEntriesResponse`|`AppendEntriesResponse`|drop the existing event|
|`AppendEntriesResponse`|`RequestVoteRequest`|drop the existing event|
|`AppendEntriesResponse`|`RequestVoteResponse`|drop the existing event|
|`RequestVoteRequest`|`AppendEntriesRequest`|drop the existing event|
|`RequestVoteRequest`|`AppendEntriesResponse`|drop the existing event|
|`RequestVoteRequest`|`RequestVoteRequest`|drop the existing event|
|`RequestVoteRequest`|`RequestVoteResponse`|drop the existing event*|
|`RequestVoteResponse`|`AppendEntriesRequest`|drop the existing event|
|`RequestVoteResponse`|`AppendEntriesResponse`|drop the existing event|
|`RequestVoteResponse`|`RequestVoteRequest`|drop the existing event|
|`RequestVoteResponse`|`RequestVoteResponse`|drop the existing event|

**Comment by danburkert** [comment]
oops

**Comment by Hoverbear** [comment]
This looks good to me and is accurate according to our discussions.

**Comment by posix4e** [comment]
What's the mechanism for preventing a server which thinks it is in leaderstate from serving stale replicas? I think diego recommends disabling the rpc if a heartbeat hasn't been heard in some time. Of course there's always quorum reads (but then why use raft at all)

**Comment by Hoverbear** [comment]
Disabling RPC as in not responding at all?

**Comment by danburkert** [comment]
@posix4e: the only way to ensure that a read is not stale is to 1) serve it from a master, 2) have the master delay responding to the request until after the next successful append-entries event.  This (short of some optimizations which don't fundamentally change the situation) is the only way to guarantee a non-stale read, since raft allows multiple concurrent masters.  This is, incidentally, what Aphyr's Call Me Maybe Analysis revealed as weaknesses in some raft implementations.  This raft implementation does not properly support this right now.

**Comment by posix4e** [comment]
Right! Leaders are only unique per term

**Comment by posix4e** [comment]
That sounds great! Any plans for compaction?

**Comment by Hoverbear** [comment]
@posix4e With this new architecture that is definitely in the cards. We haven't implemented it yet but because of how we abstract the log it will be something consuming applications can implement.

**Comment by Hoverbear** [comment]
I pulled some of these comments into the source with 81c4817036014ae0b7743c6d2449e80dc830184e. @danburkert Should we close this?

**Comment by danburkert** [comment]
Sounds good to me.
