### ISSUE TITLE
How to Handle Client Requests

### ISSUE THREAD

**Issue by Hoverbear** [Hoverbear/raft#5]
I'm currently struggling with how to properly handle the requests the "client" application makes to the library. [Code here](https://github.com/Hoverbear/raft/blob/master/src/lib.rs#L418)

How does a Follower of Raft handle this request? The Raft paper suggest a redirect, but I think this could be handled better.

**Comment by Manishearth** [comment]
Another way to do this is to internally forward the request to the leader, however this makes a more brittle connection. Returning an error; `ERR_REDIRECT` or something, with a host/port seems better to me.

**Comment by Hoverbear** [comment]
@Manishearth Currently I'm looking to transparently forward a request from a `Follower` to it's `Leader`, what do you mean by 'brittle'?

**Comment by Manishearth** [comment]
If the follower goes down, it will break :)

**Comment by Hoverbear** [comment]
@Manishearth If the follower goes down then the node won't be making requests anyways. :)

**Comment by Manishearth** [comment]
@Hoverbear Not if the follower tells the node the IP of the leader beforehand :)

**Comment by Hoverbear** [comment]
@Manishearth Right, but if the follower goes down the consuming application on that node will have crashed too, yes?

**Comment by Manishearth** [comment]
What do you mean by a node here?

**Comment by Hoverbear** [comment]
@Manishearth The library/application pair. Hmm.. I need to think about this.

**Comment by Hoverbear** [comment]
We talked about this on IRC today for a bit and come up with these thoughts:
```
<hoverbear> So we agree that raft should act as an event emitter to the client (Our state machine)?
<dcb> yes
<hoverbear> And we're undetermined on if client requests should go over network, but yes we think that might be the right idea since that's how the raft paper describes it?
<dcb> yep, I'm quite sure it has to touch the network in at least some cases, if not most
<hoverbear> dcb: Yes, I think so too. So it might be best for the leader to just express interest in a second socket through mio or something. We can discuss this more.
```

**Comment by Hoverbear** [comment]
It was determined that we'd do something along the lines of

```
consuming application <-> Raft <-> RaftNode <-> {State | StateMachine}
```
