### ISSUE TITLE
Taming the Tick

### ISSUE THREAD

**Issue by Hoverbear** [Hoverbear/raft#6]
**Goal:** Dump the `tick()` and use a proper event loop that uses `epoll` or some other readiness.

[`mio`](https://github.com/carllerche/mio/) is the obvious and probably best choice. However it's undergoing a [reform](https://github.com/carllerche/mio/pull/127). Might be best to wait till it's settled a bit.

**Comment by carllerche** [comment]
The "reform" is going quite well (though not done yet). I'd be happy to chat about mio when you are ready.

**Comment by Hoverbear** [comment]
@carllerche Had a great time exploring MIO tonight, was really impressed. Wrote about it [here](http://www.hoverbear.org/2015/03/04/getting-acquainted-with-mio/). Thanks for working on such a great library! I can see so many uses.
