### ISSUE TITLE
SOSP'2015 Poster Submission

### ISSUE THREAD

**Issue by Hoverbear** [Hoverbear/raft#69]
@ycoady suggested we consider submitting a poster to SOSP'2015!

**Location:** Monterey, California, USA
**Submission deadline (HARD, NO EXTENSIONS):** July 31, 2015 (23:59PM PDT)
**Acceptance notification:** August 7, 2015
**Conference:** October 4-7, 2015

Details:
http://www.ssrc.ucsc.edu/sosp15/callForPosters.html

## Abstract ##
> Title: A Rust-Hulled Raft
> Authors: Dan Burkert, Yvonne Coady (University of Victoria), Andrew Hobden (University of Victoria, undergraduate student, will present), James McGlashan
> Demonstration: Possible and prepared, but not necessary.
>
> Though the design of Ongaro and Osterhouts's Raft algorithm dramatically improves on the understandability of consensus algorithms relative to Paxos, it's implementation can still be relatively challenging to validate and verify.  Part of the problem is merely the chronic case of infrastructure bugs Engler identified in low level systems.  By leveraging language-level mechanisms, many implementations such as those in Go, Java, C++, Scala, Erlang, and others, are remaining true to the original Raft design but ultimately compromising on performance or understandability.  Our work aims at using Rust to build a fast, low level implementation that corresponds directly to the original design.
>
> Specifically, the Raft library interfaces with custom or preexisting Log and State Machine implementations, providing a Client, Server, and Consensus Module within its core. We have chosen an asynchronous single threaded event loop model in the Rust language, allowing our implementation to have strong safety and performance characteristics with low demands. Communication, a primary performance concern, is kept as lightweight and fast as possible by using Renshaw's Cap'n Proto implementation. Our implementation features over 85% code coverage and initial benchmarking on the `Consensus` module (no network traffic) shows a proposal to a single node cluster takes 7,436±707 ns, and in a 7 node cluster 114,808±8,859 ns. `TODO: Talk about performance tests and testing. Absolutely---if it is possible to show yours relative to any of the others on the Raft page, that would ROCK! Updating your row there before submitting would be great as well!` We are currently exploring opportunities in trust and security as well as testing our implementation for further failure conditions.  Our Rust-based Raft consensus has been a community based collaboration, and is currently scheduled as the topic for a Rust Meetup at Mozila Headquarters in late August (note to reviewers:  we will be including the feedback from this community in our poster if it is accepted, as well as expanding and improving benchmarking measurements).

## Poster
![raft poster 4](https://cloud.githubusercontent.com/assets/130903/9018844/560e4a68-3798-11e5-8983-9fae6a05d46f.jpg)

**Comment by Hoverbear** [comment]
A bit to introduce the 1 page abstract:

> Today our systems operate in extreme conditions, functioning across containers, virtual machines, infrastructure, networks, embedded systems, in our pockets, and even inside of us. Many of these systems depend on one another for operation, others are able to operate in failing connectivity without disaster. In many cases it is preferable to have the latter, especially if the operation the continued operation of the system is at stake. Distributed consensus represents one small part of a larger system, and offer the ability to maintain a replicated persistent log containing actions that are applied globally into a state machine. This allows n clients to communicate to a cluster of m servers in a stable and predictable manner, even in failing network conditions.
> Using Ongaro and Osterhouts's Raft algorithm we are developing a fast, low level, low demands implementation of the system in an opinionated, minimal way. The Raft library interfaces with custom or preexisting Log and State Machine implementations, providing a Client, Server, and Consensus Module within its core. We have chosen an asynchronous single threaded event loop model in the Rust language, allowing our implementation to have strong safety and performance characteristics with low demands. Communication, a primary performance concern, is kept as lightweight and fast as possible by using Rensha's Cap'n Proto implementation. `TODO: Talk about performance tests and testing.` We are currently exploring opportunities in trust and security as well as testing our implementation for further failure conditions.

**Comment by ycoady** [comment]
**love** it... 
making a mess with a few questions and edits, feel free to ignore!

Today our systems operate in extreme conditions, functioning across containers, virtual machines, infrastructure, networks, embedded systems, in our pockets, and even inside of us. Many of these systems depend on one another for operation, while others are able to operate in failing connectivity without disaster. In many cases it is preferable to have the latter, especially if the continued operation of the system is at stake. Distributed consensus represents one small part of a larger system, and offers the ability to maintain a replicated persistent log containing actions that are applied globally into a state machine. This allows n clients to communicate to a cluster of m servers in a stable and predictable manner, even in failing network conditions.  `Could be worth mentioning something about how the complexity of Paxos was uninviting, but now many more researchers are diving in with many more languages... or something?!`

Using Ongaro and Osterhouts's Raft algorithm we are developing a fast, low level, low demands implementation of the system in an opinionated, minimal way.  `Might be worth clarifying exactly what you mean by "low demands" and "opinionated"?`  The Raft library interfaces with custom or preexisting Log and State Machine implementations, providing a Client, Server, and Consensus Module within its core. We have chosen an asynchronous single threaded event loop model in the Rust language, allowing our implementation to have strong safety and performance characteristics with low demands.  Communication, a primary performance concern, is kept as lightweight and fast as possible by using Rensha's Cap'n Proto implementation. `TODO: Talk about performance tests and testing.  Absolutely---if it is possible to show yours relative to any of the others on the Raft page, that would ROCK!  Updating your row there before submitting would be great as well!`  We are currently exploring opportunities in trust and security as well as testing our implementation for further failure conditions.

**b e a u t i f u l !**

**Comment by dwrensha** [comment]
s/Rensha/David Renshaw/

**Comment by Hoverbear** [comment]
@dwrensha Gosh darnit I do that **all the time**, I'm so sorry!

From your twitter:

> @dwrensha
>
>The 'w' comes earlier than you'd think!

**Comment by Hoverbear** [comment]
@ycoady Once we get more features working and have more battle testing doing some performance measurements would be very useful, yeah. I remember Min was working on a consensus tester!

**Comment by Hoverbear** [comment]
> Today our systems operate in extreme conditions, functioning across containers, virtual machines, infrastructure, networks, embedded systems, in our pockets, and even inside of us. Many of these systems depend on one another for operation, others are able to operate in failing connectivity without disaster. In many cases it is preferable to have the latter, especially if the operation the continued operation of the system is at stake. Distributed consensus represents one small part of a larger system, and offer the ability to maintain a replicated persistent log containing actions that are applied globally into a state machine. This allows `n` clients to communicate to a cluster of `m` servers in a stable and predictable manner, even in failing network conditions.
> Using Ongaro and Osterhouts's Raft algorithm we are developing a fast, low level, low requirements implementation of the system in an unopinionated, minimal way. The Raft library interfaces with custom or preexisting Log and State Machine implementations, providing a Client, Server, and Consensus Module within its core. We have chosen an asynchronous single threaded event loop model in the Rust language, allowing our implementation to have strong safety and performance characteristics with low demands. Communication, a primary performance concern, is kept as lightweight and fast as possible by using Renshaw's Cap'n Proto implementation. 
> Our implementation currently features over 85% code coverage and a suite of functional tests. `TODO: Talk about performance tests.` We are currently exploring opportunities in trust and security as well as testing our implementation for further failure conditions. It is our goal to produce a high quality, well documented, flexible module that is easy to integrate with new and existing systems.

**Comment by Hoverbear** [comment]
We've been having some fun with this:

![raft poster](https://cloud.githubusercontent.com/assets/130903/8988797/3d78df3c-369d-11e5-8ad1-2eed34cd51cc.jpg)

**Comment by Hoverbear** [comment]
Okay this is rather fun:

![raft poster 1](https://cloud.githubusercontent.com/assets/130903/8988843/72a8e01c-369d-11e5-93ed-41ce3d810f79.jpg)

**Comment by Hoverbear** [comment]
@james-darkfox want to be included in on this? No obligations from you other than keep contributing! :)

**Comment by Hoverbear** [comment]
![raft poster 2](https://cloud.githubusercontent.com/assets/130903/8991637/abad57a6-36ae-11e5-9047-ab7af710af78.jpg)

**Comment by james-darkfox** [comment]
@Hoverbear Sure!

**Comment by Hoverbear** [comment]
Updated abstract with @ycoady's feedback.

**Comment by Hoverbear** [comment]
Updated poster and abstract with some initial benchmarks. The abstract is too darn long!

**Comment by Hoverbear** [comment]
We submitted this! Closing for now. If we get accepted I'll open a new issue!

**Comment by Hoverbear** [comment]
The poster was rejected.

**Comment by james-darkfox** [comment]
Rejected due to any reason specified or undisclosed why?
